/*
 * Amro Abdelrhman
 * 25/10/2019
 * this program do something 
 */

/**
 *
 * @author amabd7808
 */
public class math extends javax.swing.JFrame {

    /**
     * Creates new form math
     */
    public math() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        labeltitle = new javax.swing.JLabel();
        labelpoint1 = new javax.swing.JLabel();
        textfieldpoint1num1 = new javax.swing.JTextField();
        textfieldpoint1num2 = new javax.swing.JTextField();
        buttonpoint1 = new javax.swing.JButton();
        textfieldans1 = new javax.swing.JTextField();
        labelpoint2 = new javax.swing.JLabel();
        buttonpoint2 = new javax.swing.JButton();
        textfieldans2 = new javax.swing.JTextField();
        textfieldpoint2num1 = new javax.swing.JTextField();
        textfieldpoint2num2 = new javax.swing.JTextField();
        textfieldans3 = new javax.swing.JTextField();
        textfieldpoint3num1 = new javax.swing.JTextField();
        textfieldpoint3num2 = new javax.swing.JTextField();
        labelpoint3 = new javax.swing.JLabel();
        buttonpoint3 = new javax.swing.JButton();
        textfieldans4 = new javax.swing.JTextField();
        textfieldpoint4num1 = new javax.swing.JTextField();
        textfieldpoint4num2 = new javax.swing.JTextField();
        labelpoint4 = new javax.swing.JLabel();
        buttonpoint4 = new javax.swing.JButton();
        textfieldans5 = new javax.swing.JTextField();
        textfieldpoint5num1 = new javax.swing.JTextField();
        labelpoint5 = new javax.swing.JLabel();
        buttonpoint5 = new javax.swing.JButton();
        textfieldans6 = new javax.swing.JTextField();
        textfieldpoint6num1 = new javax.swing.JTextField();
        labelpoint6 = new javax.swing.JLabel();
        buttonpoint6 = new javax.swing.JButton();
        textfieldans7 = new javax.swing.JTextField();
        textfieldpoint7num1 = new javax.swing.JTextField();
        labelpoint7 = new javax.swing.JLabel();
        buttonpoint7 = new javax.swing.JButton();
        textfieldans8 = new javax.swing.JTextField();
        textfieldpoint8num1 = new javax.swing.JTextField();
        labelpoint8 = new javax.swing.JLabel();
        buttonpoint8 = new javax.swing.JButton();
        textfieldbyebye = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labeltitle.setFont(new java.awt.Font("ZapfEllipt BT", 1, 36)); // NOI18N
        labeltitle.setForeground(new java.awt.Color(51, 0, 153));
        labeltitle.setText("Magical Math Methods");

        labelpoint1.setText("• Enter two numbers and click the buttom. this program wil display the largest of the two numbers ");

        textfieldpoint1num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldpoint1num2ActionPerformed(evt);
            }
        });

        buttonpoint1.setText("calculate");
        buttonpoint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpoint1ActionPerformed(evt);
            }
        });

        labelpoint2.setText("• Enter two numbers and click the buttom. this program wil display the smallest of the two numbers ");

        buttonpoint2.setText("calculate");
        buttonpoint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpoint2ActionPerformed(evt);
            }
        });

        textfieldpoint2num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldpoint2num2ActionPerformed(evt);
            }
        });

        textfieldpoint3num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldpoint3num2ActionPerformed(evt);
            }
        });

        labelpoint3.setText("• Enter two numbers and click the buttom. this program wil display the first number to the power of the second ");

        buttonpoint3.setText("calculate");
        buttonpoint3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpoint3ActionPerformed(evt);
            }
        });

        textfieldpoint4num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldpoint4num2ActionPerformed(evt);
            }
        });

        labelpoint4.setText("• Enter the two sides of a right angle triangle. this program wil display hypotenus of this triangle");

        buttonpoint4.setText("calculate");
        buttonpoint4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpoint4ActionPerformed(evt);
            }
        });

        textfieldpoint5num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldpoint5num1ActionPerformed(evt);
            }
        });

        labelpoint5.setText("• Enter a decimal value. this program wil display the rounded up to the nearst integer");

        buttonpoint5.setText("calculate");
        buttonpoint5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpoint5ActionPerformed(evt);
            }
        });

        textfieldpoint6num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldpoint6num1ActionPerformed(evt);
            }
        });

        labelpoint6.setText("• Enter a decimal value. this program wil display the rounded down to the nearst integer");

        buttonpoint6.setText("calculate");
        buttonpoint6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpoint6ActionPerformed(evt);
            }
        });

        textfieldpoint7num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldpoint7num1ActionPerformed(evt);
            }
        });

        labelpoint7.setText("• Enter an integer. this program wil display the square root of the integer");

        buttonpoint7.setText("calculate");
        buttonpoint7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpoint7ActionPerformed(evt);
            }
        });

        textfieldpoint8num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldpoint8num1ActionPerformed(evt);
            }
        });

        labelpoint8.setText("• Enter an angle in degree. this program wil display the angle in redians");

        buttonpoint8.setText("calculate");
        buttonpoint8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpoint8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(labeltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(textfieldpoint1num1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(textfieldpoint1num2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(buttonpoint1)
                        .addGap(48, 48, 48)
                        .addComponent(textfieldans1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelpoint2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelpoint1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(textfieldpoint2num1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(textfieldpoint2num2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(buttonpoint2)
                        .addGap(47, 47, 47)
                        .addComponent(textfieldans2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelpoint3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelpoint4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelpoint5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelpoint6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelpoint7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelpoint8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(textfieldpoint3num1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(textfieldpoint3num2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(buttonpoint3)
                                        .addGap(48, 48, 48)
                                        .addComponent(textfieldans3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(textfieldpoint4num1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(textfieldpoint4num2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(buttonpoint4)
                                        .addGap(48, 48, 48)
                                        .addComponent(textfieldans4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(textfieldpoint5num1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addComponent(buttonpoint5)
                                        .addGap(48, 48, 48)
                                        .addComponent(textfieldans5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(textfieldpoint6num1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(buttonpoint6)
                                .addGap(48, 48, 48)
                                .addComponent(textfieldans6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(textfieldpoint7num1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(buttonpoint7)
                                .addGap(48, 48, 48)
                                .addComponent(textfieldans7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(textfieldpoint8num1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(buttonpoint8)
                                .addGap(48, 48, 48)
                                .addComponent(textfieldans8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textfieldbyebye, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labeltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelpoint1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldpoint1num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldpoint1num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonpoint1)
                    .addComponent(textfieldans1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelpoint2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldpoint2num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldpoint2num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonpoint2)
                    .addComponent(textfieldans2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelpoint3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldpoint3num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldpoint3num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonpoint3)
                    .addComponent(textfieldans3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelpoint4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldpoint4num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldpoint4num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonpoint4)
                    .addComponent(textfieldans4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelpoint5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldpoint5num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonpoint5)
                    .addComponent(textfieldans5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelpoint6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldpoint6num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonpoint6)
                    .addComponent(textfieldans6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelpoint7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldpoint7num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonpoint7)
                    .addComponent(textfieldans7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelpoint8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldpoint8num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonpoint8)
                    .addComponent(textfieldans8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(textfieldbyebye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldpoint1num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldpoint1num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldpoint1num2ActionPerformed

    private void buttonpoint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpoint1ActionPerformed
    int p1num1  ;
    int p1num2 ;
    p1num1 = Integer.parseInt(textfieldpoint1num1.getText());
    p1num2 = Integer.parseInt(textfieldpoint1num2.getText());  

textfieldans1.setText(""+Math.max(p1num1, p1num2)+"") ;
textfieldbyebye.setText("Question 1 is done ") ;
    }//GEN-LAST:event_buttonpoint1ActionPerformed

    private void buttonpoint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpoint2ActionPerformed
    int p2num1  ;
    int p2num2 ;
    p2num1 = Integer.parseInt(textfieldpoint2num1.getText());
    p2num2 = Integer.parseInt(textfieldpoint2num2.getText());  

textfieldans2.setText(""+Math.min(p2num1, p2num2)+"") ;
textfieldbyebye.setText("Question 2 is done ") ;
    }//GEN-LAST:event_buttonpoint2ActionPerformed

    private void textfieldpoint2num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldpoint2num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldpoint2num2ActionPerformed

    private void textfieldpoint3num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldpoint3num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldpoint3num2ActionPerformed

    private void buttonpoint3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpoint3ActionPerformed
    int p3num1  ;
    int p3num2 ;
    p3num1 = Integer.parseInt(textfieldpoint3num1.getText());
    p3num2 = Integer.parseInt(textfieldpoint3num2.getText());
   
    textfieldans3.setText(""+Math.pow(p3num1, p3num2)+"") ;
    textfieldbyebye.setText("Question 3 is done ") ;
    }//GEN-LAST:event_buttonpoint3ActionPerformed

    private void textfieldpoint4num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldpoint4num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldpoint4num2ActionPerformed

    private void buttonpoint4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpoint4ActionPerformed
    int p4num1  ;
    int p4num2 ;
    p4num1 = Integer.parseInt(textfieldpoint4num1.getText());
    p4num2 = Integer.parseInt(textfieldpoint4num2.getText());  

textfieldans4.setText(""+Math.hypot(p4num1, p4num2)+"") ;
textfieldbyebye.setText("Question 4 is done ") ;
    }//GEN-LAST:event_buttonpoint4ActionPerformed

    private void textfieldpoint5num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldpoint5num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldpoint5num1ActionPerformed

    private void buttonpoint5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpoint5ActionPerformed
    double p5num1  ;
    p5num1 = Double.parseDouble(textfieldpoint5num1.getText());  

textfieldans5.setText(""+Math.round(p5num1)+"") ; 
textfieldbyebye.setText("Question 5 is done ") ;
    }//GEN-LAST:event_buttonpoint5ActionPerformed

    private void textfieldpoint6num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldpoint6num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldpoint6num1ActionPerformed

    private void buttonpoint6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpoint6ActionPerformed
double p6num1  ;
    p6num1 = Double.parseDouble(textfieldpoint6num1.getText());  

textfieldans6.setText(""+Math.floor(p6num1)+"") ; 
textfieldbyebye.setText("Question 6 is done ") ;
    }//GEN-LAST:event_buttonpoint6ActionPerformed

    private void textfieldpoint7num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldpoint7num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldpoint7num1ActionPerformed

    private void buttonpoint7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpoint7ActionPerformed
double p7num1  ;
    p7num1 = Double.parseDouble(textfieldpoint7num1.getText());  

textfieldans7.setText(""+Math.sqrt(p7num1)+"") ; 
textfieldbyebye.setText("Question 7 is done ") ;
    }//GEN-LAST:event_buttonpoint7ActionPerformed

    private void textfieldpoint8num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldpoint8num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldpoint8num1ActionPerformed

    private void buttonpoint8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpoint8ActionPerformed
double p8num1  ;
    p8num1 = Double.parseDouble(textfieldpoint8num1.getText());  

textfieldans8.setText(""+Math.toRadians(p8num1)+"") ; 
textfieldbyebye.setText("your are done ") ; 
    }//GEN-LAST:event_buttonpoint8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(math.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(math.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(math.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(math.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new math().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonpoint1;
    private javax.swing.JButton buttonpoint2;
    private javax.swing.JButton buttonpoint3;
    private javax.swing.JButton buttonpoint4;
    private javax.swing.JButton buttonpoint5;
    private javax.swing.JButton buttonpoint6;
    private javax.swing.JButton buttonpoint7;
    private javax.swing.JButton buttonpoint8;
    private javax.swing.JLabel labelpoint1;
    private javax.swing.JLabel labelpoint2;
    private javax.swing.JLabel labelpoint3;
    private javax.swing.JLabel labelpoint4;
    private javax.swing.JLabel labelpoint5;
    private javax.swing.JLabel labelpoint6;
    private javax.swing.JLabel labelpoint7;
    private javax.swing.JLabel labelpoint8;
    private javax.swing.JLabel labeltitle;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField textfieldans1;
    private javax.swing.JTextField textfieldans2;
    private javax.swing.JTextField textfieldans3;
    private javax.swing.JTextField textfieldans4;
    private javax.swing.JTextField textfieldans5;
    private javax.swing.JTextField textfieldans6;
    private javax.swing.JTextField textfieldans7;
    private javax.swing.JTextField textfieldans8;
    private javax.swing.JTextField textfieldbyebye;
    private javax.swing.JTextField textfieldpoint1num1;
    private javax.swing.JTextField textfieldpoint1num2;
    private javax.swing.JTextField textfieldpoint2num1;
    private javax.swing.JTextField textfieldpoint2num2;
    private javax.swing.JTextField textfieldpoint3num1;
    private javax.swing.JTextField textfieldpoint3num2;
    private javax.swing.JTextField textfieldpoint4num1;
    private javax.swing.JTextField textfieldpoint4num2;
    private javax.swing.JTextField textfieldpoint5num1;
    private javax.swing.JTextField textfieldpoint6num1;
    private javax.swing.JTextField textfieldpoint7num1;
    private javax.swing.JTextField textfieldpoint8num1;
    // End of variables declaration//GEN-END:variables
}
