/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Scanner ;
/**
 *
 * @author amabd7808
 */
public class zirboin extends javax.swing.JFrame {
 
    /**
     * Creates new form zirboin
     */
    public zirboin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        lblq1 = new javax.swing.JLabel();
        txtfvrobits = new javax.swing.JTextField();
        lbldrobzits = new javax.swing.JLabel();
        txtfdrobzits = new javax.swing.JTextField();
        lblclickwick = new javax.swing.JLabel();
        txtfclickwick = new javax.swing.JTextField();
        lblgazoontight = new javax.swing.JLabel();
        txtfgazoontight = new javax.swing.JTextField();
        lblfrazoint = new javax.swing.JLabel();
        txtffrazoint = new javax.swing.JTextField();
        lblblointoint = new javax.swing.JLabel();
        txtfblointoint = new javax.swing.JTextField();
        lblleftover = new javax.swing.JLabel();
        txtfleftover = new javax.swing.JTextField();
        btncalculate = new javax.swing.JButton();
        txtfcomment = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitle.setFont(new java.awt.Font("TimelessTCYLig", 1, 18)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(0, 153, 102));
        lbltitle.setText("Zirboin Bank");

        lblq1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblq1.setText("Please write down the amount of vrobit do you have ");

        lbldrobzits.setText("Drobzits");

        lblclickwick.setText("Clckwick");

        lblgazoontight.setText("gavoontight");

        txtfgazoontight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfgazoontightActionPerformed(evt);
            }
        });

        lblfrazoint.setText("Frazoint");

        lblblointoint.setText("blointoint");

        lblleftover.setText("Left over");

        btncalculate.setText("Calculate");
        btncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelLayout.createSequentialGroup()
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelLayout.createSequentialGroup()
                                            .addGap(135, 135, 135)
                                            .addComponent(txtfclickwick, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelLayout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addComponent(txtfdrobzits, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(28, 28, 28)
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblgazoontight)
                                        .addComponent(txtfgazoontight, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtfleftover, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btncalculate))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtffrazoint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                    .addComponent(lblfrazoint)
                                    .addGap(13, 13, 13))))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(lblq1)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblclickwick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(txtfblointoint, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(lbltitle))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(txtfvrobits, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbldrobzits)
                .addGap(153, 153, 153)
                .addComponent(lblleftover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblblointoint)
                .addGap(53, 53, 53))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtfcomment, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblq1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfvrobits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btncalculate)
                .addGap(18, 18, 18)
                .addComponent(lblgazoontight)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblclickwick)
                            .addComponent(lblfrazoint))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfclickwick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtffrazoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfgazoontight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblleftover)
                    .addComponent(lblblointoint)
                    .addComponent(lbldrobzits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfblointoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfdrobzits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfleftover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(txtfcomment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfgazoontightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfgazoontightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfgazoontightActionPerformed

    private void btncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculateActionPerformed
    Scanner keyedInput = new Scanner (System.in);
    double [ ] newtotal = new double [5];
    double vrobits;
    double [ ] drobzit = new double [2];
    double [ ] clickwick = new double [2];
    double [ ] gazoontight = new double [2];
    double [ ] frazoint = new double [2];
    double [ ] blointoint = new double [2];
    vrobits = Integer.parseInt(txtfvrobits.getText());
    drobzit[0] = vrobits/100000;
    drobzit[1] = Math.floor(drobzit[0]);
    txtfdrobzits.setText(""+drobzit[1]+"");
    newtotal[0] = (Math.abs(drobzit[0]-drobzit[1])) *vrobits;
    
    clickwick[0] = newtotal[0]/50000;
    clickwick[1] = Math.floor(clickwick[0]);
    txtfclickwick.setText(""+clickwick[1]+"");
    newtotal[1] = (Math.abs(clickwick[0]-clickwick[1]))*newtotal[0];
    
    gazoontight[0] = newtotal[1]/10000;
    gazoontight[1] = Math.floor(gazoontight[0]);
    txtfgazoontight.setText(""+gazoontight[1]+"");
    newtotal[2] = (Math.abs(gazoontight[0]-gazoontight[1]))*newtotal[1];
    
    frazoint[0] = newtotal[2]/1000;
    frazoint[1] = Math.floor(frazoint[0]);
    txtffrazoint.setText(""+frazoint[1]+"");
    newtotal[3] = (Math.abs(frazoint[0]-frazoint[1]))*newtotal[2];
    
    blointoint[0] = newtotal[3]/1000;
    blointoint[1] = Math.floor(blointoint[0]);
    txtfblointoint.setText(""+blointoint[1]+"");
    newtotal[4] = (Math.abs(blointoint[0]-blointoint[1]))*newtotal[3];
    
    txtfleftover.setText(""+newtotal[4]+"");
    txtfcomment.setText("you should of got "+drobzit[1]+" Drobzits, "+clickwick[1]+"Clickwicks, "+gazoontight[1]+"Gazoontights, "+frazoint[1]+"Frazoints, "+blointoint[1]+"Blointoints and "+newtotal[4]+"as a leftover");
    }//GEN-LAST:event_btncalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(zirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(zirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(zirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(zirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new zirboin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalculate;
    private javax.swing.JLabel lblblointoint;
    private javax.swing.JLabel lblclickwick;
    private javax.swing.JLabel lbldrobzits;
    private javax.swing.JLabel lblfrazoint;
    private javax.swing.JLabel lblgazoontight;
    private javax.swing.JLabel lblleftover;
    private javax.swing.JLabel lblq1;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtfblointoint;
    private javax.swing.JTextField txtfclickwick;
    private javax.swing.JTextField txtfcomment;
    private javax.swing.JTextField txtfdrobzits;
    private javax.swing.JTextField txtffrazoint;
    private javax.swing.JTextField txtfgazoontight;
    private javax.swing.JTextField txtfleftover;
    private javax.swing.JTextField txtfvrobits;
    // End of variables declaration//GEN-END:variables
}
